### ISSUE TITLE
Error node install

### ISSUE THREAD

**Issue by juizmill** [gonzalo123/gdb#1]
```
$ node install
module.js:338
    throw err;
          ^
Error: Cannot find module '/var/www/gdb/install'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by gonzalo123** [comment]
it's a typo error within readme. Node dependencies are installed with npm
